# Generated by Django 4.2.4 on 2023-08-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume_logs", "0002_entry_gpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="section",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="entry",
            name="gpt",
            field=models.TextField(),
        ),
    ]
