# Generated by Django 4.2.4 on 2023-08-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume_logs", "0003_entry_section_alter_entry_gpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="question_index",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
