# Generated by Django 4.2.4 on 2023-08-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume_logs", "0004_entry_question_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="question_index",
        ),
        migrations.AddField(
            model_name="topic",
            name="question_index",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
