# Generated by Django 4.2.4 on 2023-08-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume_logs", "0005_remove_entry_question_index_topic_question_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="sender",
            field=models.TextField(default="Anonymous Sender"),
        ),
    ]
