# Generated by Django 4.2.4 on 2023-08-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume_logs", "0006_entry_sender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="section",
            field=models.TextField(default=""),
        ),
    ]
