# Generated by Django 3.2.20 on 2023-08-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_logs', '0007_alter_entry_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='keyword',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
