# Generated by Django 3.2.20 on 2023-08-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_logs', '0008_entry_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='resume_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
